% Interface para Análise de Dados Raman
function interface
    % Janela principal
    fig = uifigure('Name', 'Análise de Dados Raman', 'Position', [100, 100, 800, 400]);

    % Layout da interface
    layout = uigridlayout(fig, [4, 2], ...
        'RowHeight', {25, 30, 'fit', 100}, ...
        'ColumnWidth', {'4x', '1x'}); 

    % Label para a pasta de resultados
    lblPasta = uilabel(layout, ...
        'Text', 'Pasta para salvar os resultados:', ...
        'FontWeight', 'bold', ...
        'FontSize', 14, ...
        'HorizontalAlignment', 'left');
    lblPasta.Layout.Row = 1;
    lblPasta.Layout.Column = [1 2];

    % Campo de texto
    txtField = uieditfield(layout, 'text', ...
        'Placeholder', 'Insira o nome da pasta', ...
        'FontSize', 14, ...
        'BackgroundColor', '#E6E6E6', ...
        'HorizontalAlignment', 'left');
    txtField.Layout.Row = 2;
    txtField.Layout.Column = 1;

    % Botão "Salve"
    btnSave = uibutton(layout, 'push', ...
        'Text', 'Salve', ...
        'FontSize', 16, ...
        'BackgroundColor', '#37353A', ...
        'FontColor', '#EEECDF', ...
        'ButtonPushedFcn', @(btn, event) saveCallback(txtField));
    btnSave.Layout.Row = 2;
    btnSave.Layout.Column = 2;

    % Label para "Arquivo de dados"
    lblArquivo = uilabel(layout, ...
        'Text', 'Arquivo de dados:', ...
        'FontWeight', 'bold', ...
        'FontSize', 14, ...
        'HorizontalAlignment', 'left');
    lblArquivo.Layout.Row = 3;
    lblArquivo.Layout.Column = 1;

    % Frame abaixo de "Arquivo de dados"
    frame = uipanel(layout, ...
        'BackgroundColor', '#E6E6E6', ...
        'BorderType', 'line', ...
        'Title', '');
    frame.Layout.Row = 4;
    frame.Layout.Column = [1 2];

    % Label dentro do frame para exibir o nome do arquivo na parte superior esquerda
    frameLabel = uilabel(frame, ...
        'Text', 'Nenhum arquivo selecionado', ...
        'FontSize', 12, ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ... % Alinhado ao topo
        'Position', [10, 70, 780, 20]); % Ajustado para a parte superior esquerda

    % Botão "Choose data"
    btnChooseData = uibutton(layout, 'push', ...
        'Text', 'Choose data', ...
        'FontSize', 16, ...
        'BackgroundColor', '#37353A', ...
        'FontColor', '#EEECDF', ...
        'ButtonPushedFcn', @(btn, event) chooseDataCallback(frameLabel));
    btnChooseData.Layout.Row = 3;
    btnChooseData.Layout.Column = 2;
end

% Callback para salvar a pasta
function saveCallback(txtField)
    pastaRaiz = txtField.Value;
    if isempty(pastaRaiz)
        uialert(txtField.Parent, 'Por favor, insira um nome para a pasta.', 'Erro');
        return;
    end
    caminhoSelecionado = uigetdir('', 'Selecione o caminho para salvar os resultados');
    if caminhoSelecionado == 0
        uialert(txtField.Parent, 'Nenhum caminho foi selecionado.', 'Erro');
        return;
    end
    pastaRaizCompleta = fullfile(caminhoSelecionado, pastaRaiz);
    if ~exist(pastaRaizCompleta, 'dir')
        mkdir(pastaRaizCompleta);
    end
    uialert(txtField.Parent, sprintf('Pasta "%s" configurada com sucesso!', pastaRaiz), 'Sucesso');
end

% Callback para escolher dados
function chooseDataCallback(frameLabel)
    [file, path] = uigetfile({'*.*', 'Todos os Arquivos'; ...
                              '*.csv', 'Arquivos CSV (*.csv)'; ...
                              '*.xlsx', 'Arquivos Excel (*.xlsx)'}, ...
                              'Selecione o arquivo de dados');
    if isequal(file, 0)
        frameLabel.Text = 'Nenhum arquivo selecionado';
        return;
    end
    % Atualiza o texto no frame para exibir o nome do arquivo selecionado
    frameLabel.Text = sprintf('Arquivo selecionado: %s', file);
end